source 'https://rubygems.org'

gem 'bcrypt'
gem 'bigdecimal', force_ruby_platform: true
gem 'escape_utils'
gem 'eventmachine', force_ruby_platform: true
gem 'fast-stemmer'
gem 'ffi', force_ruby_platform: true
gem 'fiddle', force_ruby_platform: true
gem 'hitimes'
gem 'json'
gem 'mini_portile2'
gem 'mysql2', force_ruby_platform: true
gem 'pact_broker-client'
gem 'pg', force_ruby_platform: true
gem 'psych', force_ruby_platform: true
gem 'puma', force_ruby_platform: true
gem 'RedCloth'
gem 'redcarpet'
gem 'rexml'
gem 'rinda'
gem 'stringio', force_ruby_platform: true
gem 'test-unit'
gem 'thin', force_ruby_platform: true
gem 'unf_ext', force_ruby_platform: true
gem 'webrick'
gem 'yajl-ruby'

## WIP - Windows ARM

gem "sqlite3", force_ruby_platform: true
gem 'nokogiri', force_ruby_platform: true
gem 'pact_broker'
gem 'rails'

# wont build on windows arm

gem 'curses', force_ruby_platform: true
gem 'rugged', force_ruby_platform: true
# unicorn requires charlock_holmes & kgio
# no support on windows (no mmap /getaddrinfo) pitchfork is a maintained fork
gem 'unicorn', force_ruby_platform: true unless Gem.win_platform?
gem 'charlock_holmes', force_ruby_platform: true unless Gem.win_platform?
gem 'kgio', force_ruby_platform: true unless Gem.win_platform?
gem 'raindrops', force_ruby_platform: true unless Gem.win_platform?