env:
  TRAVELING_RUBY_RB_VERSION: 3.2.2
  TRAVELING_RUBY_PKG_DATE: 20230523

linux_arm_docker_builder:
  env:
    CIRRUS_ARCH: arm64
    TRAVELING_RUBY_ARCHITECTURE: arm64
    TRAVELING_RUBY_PLATFORM: linux
  script: ./scripts/build.sh
  binary_artifacts:
    path: "build"

macosx-arm64_task: 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  env:
    CIRRUS_ARCH: arm64
    TRAVELING_RUBY_ARCHITECTURE: arm64
    TRAVELING_RUBY_PLATFORM: osx
  script: ./scripts/build.sh
  binary_artifacts:
    path: "build"

linux_amd_docker_builder: 
  only_if: $CIRRUS_CHANGE_TITLE =~ 'ci:.*\[x86_64\].*'
  env:
    CIRRUS_ARCH: amd64
    TRAVELING_RUBY_ARCHITECTURE: x86_64
    TRAVELING_RUBY_PLATFORM: linux
  script: ./scripts/build.sh
  binary_artifacts:
    path: "build"
    
macosx-x86_64_task: 
  only_if: $CIRRUS_CHANGE_TITLE =~ 'ci:.*\[x86_64\].*'
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  env:
    CIRRUS_ARCH: arm64
    TRAVELING_RUBY_ARCHITECTURE: x86_64
    TRAVELING_RUBY_PLATFORM: osx
    USE_ROSETTA: "true"
  script: ./scripts/build.sh
  binary_artifacts:
    path: "build"

windows_task:
  only_if: $CIRRUS_CHANGE_TITLE =~ 'ci:.*\[x86_64\].*'
  windows_container:
    image: cirrusci/windowsservercore:2019
  env:
    CIRRUS_ARCH: arm64
    TRAVELING_RUBY_ARCHITECTURE: x86_64
    TRAVELING_RUBY_PLATFORM: windows
    USE_ROSETTA: "true"
  script: ./scripts/build.sh
  binary_artifacts:
    path: "build"