name: build - x86_64
on:
  push:
    branches: [ main, ci, 3.2.2 ]

env:
  TRAVELING_RUBY_RB_VERSION: 3.2.2
  TRAVELING_RUBY_PKG_DATE: 20230523

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        arch: [x86_64]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.TRAVELING_RUBY_RB_VERSION }}
      - name: build image
        run: ./scripts/build.sh
        env:
          TRAVELING_RUBY_PKG_DATE: ${{ env.TRAVELING_RUBY_PKG_DATE }}
          TRAVELING_RUBY_PLATFORM: ${{ runner.os }}
          TRAVELING_RUBY_ARCHITECTURE: ${{ matrix.arch }}
      - name: push to dockerhub
        if: github.ref == 'refs/heads/dockerhub'
        run: |
          docker push you54f/traveling-ruby-builder-${{ matrix.arch }}:1.0
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: 'Upload Artifact - linux ${{ matrix.arch }}'
        uses: actions/upload-artifact@v3
        with:
          path: build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: build
          tag: "v${{ env.TRAVELING_RUBY_PKG_DATE }}-${{ env.TRAVELING_RUBY_RB_VERSION }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true