name: MacOS x86_64

on:
  push:
    branches: [ traveling-pact-next ]
  pull_request:
    branches: [ traveling-pact-next ]

env:
  PKG_DATE: 20240317
  PLATFORM: osx
  ARCHITECTURES: x86_64
  DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer

jobs:
  make-osx-x86_64:
    strategy:
      matrix:
        os: [macos-12]
        # ruby-version: [3.0.6] # Pre 3.1.0 builds with openssl 1.1.1
        ruby-version: [3.2.3]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: download osx x86_64 runtime
        run: ./scripts/download-osx-runtime.sh
        env:
          RUBY_VERSIONS: ${{ matrix.ruby-version }}
      - name: build x86_64
        run: |
          cd osx
          rake stash_conflicting_paths
          rake --trace
          rake unstash_conflicting_paths
          ls
        env:
          RUBY_VERSIONS: ${{ matrix.ruby-version }}
      # - name: package osx x86_64 runtime
      #   run: ./scripts/package-osx-runtime.sh
      #   env:
      #     RUBY_VERSIONS: ${{ matrix.ruby-version }}
      # - name: 'Upload Runtime - osx x86_64'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: osx-runtime-x86_64-gha-openssl_1_1.tar.gz
      #     path: osx/osx-runtime-*.tar.gz
      - name: package gems
        run: ./scripts/package-gems.sh
      - name: "Upload Artifact- osx x86_64"
        uses: actions/upload-artifact@v3
        with:
          name: traveling-pact-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-osx-x86_64.tar.gz
          path: osx/traveling-pact*.tar.gz
      - name: test
        run: |
          cd osx
          rake test
        env:
          RUBY_VERSIONS: ${{ matrix.ruby-version }}
