name: Linux - x86_64 - build image, package, publish
on:
  push:
    branches: [ main, ci, 3.2.2 ]
    paths-ignore:
      - '.circleci/**'
      - '.cirrus.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.circleci/**'
      - '.cirrus.yml'

env:
  RB_VERSION: 3.2.2
  PKG_DATE: 20230523

jobs:
  make-ubuntu-x86_64:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RB_VERSION }}
      - name: build image
        run: |
          cd linux
          rake image
          docker images
        env:
          ARCHITECTURES: ${{ matrix.arch }}
      - name: build from image
        run: |
          cd linux
          rake
        env:
          ARCHITECTURES: ${{ matrix.arch }}
      - name: push to dockerhub
        if: github.ref == 'refs/heads/dockerhub'
        run: |
          docker push you54f/traveling-ruby-builder-${{ matrix.arch }}:1.0
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: 'Upload Artifact - linux ${{ matrix.arch }}'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-${{ env.PKG_DATE }}-${{ env.RB_VERSION }}-${{ matrix.arch }}-linux.tar.gz
          path: linux/traveling-ruby-${{ env.PKG_DATE }}-${{ env.RB_VERSION }}-${{ matrix.arch }}-linux.tar.gz
      - uses: ncipollo/release-action@v1
        with:
          artifacts: linux/traveling-ruby-${{ env.PKG_DATE }}-${{ env.RB_VERSION }}-${{ matrix.arch }}-linux.tar.gz
          tag: "v${{ env.PKG_DATE }}-${{ env.RB_VERSION }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true